server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: rotas do react-router caem no index.html
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Cache de assets com hash
  location /assets/ {
    expires 30d;
    add_header Cache-Control "public, immutable";
  }
}
